export interface ClassRoutineModel {
  id?: number;           // Optional unique ID (auto-generated by backend)
  className: string;     // e.g. "Grade 8"
  subject: string;       // e.g. "Math"
  teacherId: number;     // Teacher's unique ID (assumed numeric based on Java Integer)
  teacherName?: string;  // Optional, populated when returned from backend
  dayOfWeek: string;     // e.g. "Monday"
  startTime: string;     // e.g. "09:00", format should match backend (HH:mm)
  endTime: string;       // e.g. "10:00"
}
